// Code generated by templ - DO NOT EDIT.
// Stub implementations — run `templ generate` to regenerate from integrations.templ
package web

import (
	"context"
	"fmt"
	"io"

	"github.com/a-h/templ"
	"github.com/quest-one/quest-one/internal/domain"
)

func IntegrationsPage(integrations []domain.Integration) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		body := templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
			if _, err := fmt.Fprintf(w,
				`<div class="page-header"><h1>Integrations</h1></div>`); err != nil {
				return err
			}
			if len(integrations) == 0 {
				_, err := io.WriteString(w, `<div class="empty-state">No integrations configured yet.</div>`)
				return err
			}
			if _, err := io.WriteString(w, `<div class="card">`); err != nil {
				return err
			}
			for _, i := range integrations {
				if err := IntegrationRow(i).Render(ctx, w); err != nil {
					return err
				}
			}
			_, err := io.WriteString(w, `</div>`)
			return err
		})
		return Layout("Integrations").Render(templ.WithChildren(ctx, body), w)
	})
}

func IntegrationRow(i domain.Integration) templ.Component {
	return templ.ComponentFunc(func(_ context.Context, w io.Writer) error {
		status := "disabled"
		if i.Enabled {
			status = "enabled"
		}
		_, err := fmt.Fprintf(w,
			`<div class="task-row" id="integration-%s">`+
				`<span class="task-status">%s</span>`+
				`<span class="task-title">%s <span style="color:var(--muted)">(%s)</span></span>`+
				`<div style="display:flex;gap:0.25rem">`,
			i.ID, status,
			templ.EscapeString(i.Name), i.Provider,
		)
		if err != nil {
			return err
		}
		if i.Enabled {
			_, err = fmt.Fprintf(w,
				`<button class="btn btn-sm" hx-post="/api/v1/integrations/%s/disable" `+
					`hx-target="#integration-%s" hx-swap="outerHTML">Disable</button>`,
				i.ID, i.ID,
			)
		} else {
			_, err = fmt.Fprintf(w,
				`<button class="btn btn-sm btn-primary" hx-post="/api/v1/integrations/%s/enable" `+
					`hx-target="#integration-%s" hx-swap="outerHTML">Enable</button>`,
				i.ID, i.ID,
			)
		}
		if err != nil {
			return err
		}
		_, err = fmt.Fprintf(w,
			`<button class="btn btn-sm btn-danger" hx-delete="/api/v1/integrations/%s" `+
				`hx-target="#integration-%s" hx-swap="outerHTML" `+
				`hx-confirm="Delete this integration?">Delete</button></div></div>`,
			i.ID, i.ID,
		)
		return err
	})
}
