// Code generated by templ - DO NOT EDIT.
// Stub implementations — run `templ generate` to regenerate from layout.templ
package web

import (
	"context"
	"io"

	"github.com/a-h/templ"
)

// Layout renders the shared HTML shell with children injected via ctx.
func Layout(title string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		if _, err = io.WriteString(w, `<!DOCTYPE html><html lang="en"><head>`+
			`<meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/>`+
			`<title>`); err != nil {
			return
		}
		if _, err = io.WriteString(w, templ.EscapeString(title)); err != nil {
			return
		}
		if _, err = io.WriteString(w, ` — quest-one</title>`+
			`<link rel="stylesheet" href="/static/style.css"/>`+
			`<script src="https://unpkg.com/htmx.org@1.9.12" defer></script>`+
			`</head><body><div class="layout">`+
			`<nav class="sidebar"><div class="logo">quest-one</div>`+
			`<a href="/tasks" class="nav-link">Tasks</a>`+
			`<a href="/integrations" class="nav-link">Integrations</a>`+
			`<a href="/settings" class="nav-link">Settings</a>`+
			`</nav><main class="main">`); err != nil {
			return
		}
		if err = templ.GetChildren(ctx).Render(ctx, w); err != nil {
			return
		}
		_, err = io.WriteString(w, `</main></div></body></html>`)
		return
	})
}
