// Code generated by templ - DO NOT EDIT.
// Stub implementations — run `templ generate` to regenerate from settings.templ
package web

import (
	"context"
	"fmt"
	"io"

	"github.com/a-h/templ"
	"github.com/quest-one/quest-one/internal/domain"
)

func SettingsPage(s domain.Settings) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		body := templ.ComponentFunc(func(_ context.Context, w io.Writer) error {
			_, err := fmt.Fprintf(w,
				`<h1>Settings</h1><div class="card">`+
					`<p><strong>Port:</strong> %d</p>`+
					`<p><strong>Data dir:</strong> %s</p>`+
					`<p><strong>Language:</strong> %s</p>`+
					`<p><strong>LLM Provider:</strong> %s</p>`+
					`</div>`,
				s.ServerPort,
				templ.EscapeString(s.DataDir),
				templ.EscapeString(s.Language),
				templ.EscapeString(s.LLMProvider),
			)
			return err
		})
		return Layout("Settings").Render(templ.WithChildren(ctx, body), w)
	})
}
