// Code generated by templ - DO NOT EDIT.
// Stub implementations — run `templ generate` to regenerate from tasks.templ
package web

import (
	"context"
	"fmt"
	"io"

	"github.com/a-h/templ"
	"github.com/quest-one/quest-one/internal/domain"
)

func TasksPage(tasks []domain.Task) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		body := templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
			if _, err := fmt.Fprintf(w, `<div class="page-header"><h1>Tasks</h1>`+
				`<a href="/tasks/new" class="btn btn-primary">+ New Task</a></div>`+
				`<div id="task-list">`); err != nil {
				return err
			}
			if err := TaskList(tasks).Render(ctx, w); err != nil {
				return err
			}
			_, err := io.WriteString(w, `</div>`)
			return err
		})
		return Layout("Tasks").Render(templ.WithChildren(ctx, body), w)
	})
}

func TaskList(tasks []domain.Task) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		if len(tasks) == 0 {
			_, err := io.WriteString(w, `<div class="empty-state">No tasks yet. Add one above!</div>`)
			return err
		}
		if _, err := io.WriteString(w, `<div class="card">`); err != nil {
			return err
		}
		for _, t := range tasks {
			if err := TaskRow(t).Render(ctx, w); err != nil {
				return err
			}
		}
		_, err := io.WriteString(w, `</div>`)
		return err
	})
}

func TaskRow(task domain.Task) templ.Component {
	return templ.ComponentFunc(func(_ context.Context, w io.Writer) error {
		actions := ""
		if task.IsActive() {
			actions = fmt.Sprintf(
				`<div style="display:flex;gap:0.25rem">`+
					`<button class="btn btn-sm" hx-post="/tasks/%s/promote" hx-target="#task-%s" hx-swap="outerHTML">↑</button>`+
					`<button class="btn btn-sm btn-primary" hx-post="/tasks/%s/complete" hx-target="#task-%s" hx-swap="outerHTML">✓</button>`+
					`</div>`,
				task.ID, task.ID, task.ID, task.ID,
			)
		}
		_, err := fmt.Fprintf(w,
			`<div class="task-row" id="task-%s">`+
				`<span class="task-status status-%s">%s</span>`+
				`<a href="/tasks/%s" class="task-title">%s</a>`+
				`%s</div>`,
			task.ID, task.Status, task.Status,
			task.ID, templ.EscapeString(task.Title),
			actions,
		)
		return err
	})
}

func NewTaskPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		body := templ.ComponentFunc(func(_ context.Context, w io.Writer) error {
			_, err := io.WriteString(w, `<h1>New Task</h1><div class="card">`+
				`<form hx-post="/tasks" hx-target="#task-list" hx-swap="beforeend">`+
				`<div class="form-group"><label for="title">Title *</label>`+
				`<input id="title" name="title" type="text" required/></div>`+
				`<div class="form-group"><label for="description">Description</label>`+
				`<textarea id="description" name="description"></textarea></div>`+
				`<button type="submit" class="btn btn-primary">Add Task</button>`+
				`<a href="/tasks" class="btn" style="margin-left:0.5rem">Cancel</a>`+
				`</form></div>`)
			return err
		})
		return Layout("New Task").Render(templ.WithChildren(ctx, body), w)
	})
}

func TaskDetailPage(task domain.Task) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		body := templ.ComponentFunc(func(_ context.Context, w io.Writer) error {
			_, err := fmt.Fprintf(w,
				`<div class="page-header"><h1>%s</h1>`+
					`<span class="task-status status-%s">%s</span></div>`+
					`<div class="card"><p style="color:var(--muted)">%s</p>`+
					`<p style="margin-top:0.5rem;color:var(--muted);font-size:0.8rem">Created %s</p></div>`,
				templ.EscapeString(task.Title),
				task.Status, task.Status,
				templ.EscapeString(task.Description),
				task.CreatedAt.Format("2006-01-02 15:04"),
			)
			if err != nil {
				return err
			}
			if task.IsActive() {
				_, err = fmt.Fprintf(w,
					`<div class="card"><h2>Actions</h2><div style="display:flex;gap:0.5rem">`+
						`<button class="btn btn-sm" hx-post="/tasks/%s/promote" hx-target="body">↑ Promote</button>`+
						`<button class="btn btn-sm btn-primary" hx-post="/tasks/%s/complete" hx-target="body">✓ Complete</button>`+
						`<button class="btn btn-sm btn-danger" hx-post="/tasks/%s/cancel" hx-target="body">✕ Cancel</button>`+
						`</div></div>`,
					task.ID, task.ID, task.ID,
				)
				if err != nil {
					return err
				}
			}
			_, err = fmt.Fprintf(w,
				`<div class="card"><h2>Memo</h2>`+
					`<form hx-post="/tasks/%s/memo" hx-target="body">`+
					`<div class="form-group"><textarea name="memo">%s</textarea></div>`+
					`<button type="submit" class="btn btn-sm btn-primary">Save Memo</button>`+
					`</form></div>`,
				task.ID, templ.EscapeString(task.Memo),
			)
			return err
		})
		return Layout(task.Title).Render(templ.WithChildren(ctx, body), w)
	})
}
